version: 2
sources:
- name: RAW
  schema: gz_rwa_data
  tables:
    - name: sales
      identifier: gz_raw_sales
      description: revenue per order
      freshness:
       warn_after:
          count: 90
          period: day
      loaded_at_field: "CAST(date_date AS TIMESTAMP)"
      columns:
        - name: date_date
        - name: revenue
        - name: quantity
        - name: primary_key
    - name: product
      identifier: gz_raw_product
      description: purchase price per product id
      columns:
        - name: products_id
          description: primary key
          tests:
           - unique
           - not_null
        - name: purchase_price
    - name: ship
      identifier: gz_raw_ship
      description: shipping details per order
      columns:
        - name: orders_id
          description: primary key
          tests:
            - unique
            - not_null
        - name: ship_cost
        - name: shipping_fee
        - name: logcost
    - name : adwords
      identifier: raw_gz_adwords
      description : data for adwords
      columns:
        - name: campaign_key
          description: primary key
          tests:
            - unique
            - not null
    - name: bing
      identifier: raw_gz_bing
      description: data from bing
      columns:
        - name: campaign_key
          description: primary key
          tests:
            - unique
            - not null
    - name: criteo
      identifier: raw_gz_criteo
      description: data from criteo
      columns:
        - name: campaign_key
          description: primary key
          tests:
            - unique
            - not null
    - name: facebook
      identifier: raw_gz_facebook
      columns:
        - name: campaign_key
          description: primary key
          tests:
            - unique
            - not null

models:
 - name: stg_raw__sales
   columns:
    - name: primary_key
      tests:
      - unique
      - not_null