version : 2

sources:
  - name: RAW
    schema: gz_rwa_data
    tables:
      - name: sales
        identifier: gz_raw_sales
      - name: product
        identifier: gz_raw_product
      - name: ship
        identifier: gz_raw_ship